AWSTemplateFormatVersion: 2010-09-09
Description: Exercise AWS S3 CLI Security - S3 Buckets (for seven objects with varying policies) for Participants
Resources:
  S3BUCKETNAME:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}'
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
         Rules:
         - ObjectOwnership: BucketOwnerPreferred
